### PR TITLE
Docker Compose and Caddyfile

### PR DESCRIPTION
**Pull request by rushsteve1**
- Wrote an initial `docker-compose.yml` file for future deployments, and updated the `README` and roles files to go with it.
- Removed the `postgrest.conf` file since PostgREST is now configured through environment variables in the compose file.
- Renamed the `postgrest` folder to `examples` since it now just contains the client example.

---

**Looking for feedback on this PR since it's the initial infrastructure setup and is more nebulous.**

---

Things left to do:

- [x] Create the Wiki database and setup Postgres role
- [x] Configuration for the Wiki
- [ ] Figure out more useful Caddy logging (that doesn't get too full over time)
- [ ] Setup running some version of Observatory in the compose file and Caddy rules
- [x] Test and deploy everything!

### CODE REVIEW

**Comment by Apexal** [comment]
I'm unfortunately not super familiar with Docker and its ecosystem. It looks like Caddy will let us run multiple apps on the same host on different ports, and map <service>.rcos.io to them?

**Comment by Apexal** [comment]
One important question: How soon can this be deployed? How many things have to be done? Do we need access to rcos.io, the right DigitalOcean, etc. before any of this can go up? What if that doesn't happen by the start of the semester?

**Comment by rushsteve1** [comment]
> I'm unfortunately not super familiar with Docker and its ecosystem. It looks like Caddy will let us run multiple apps on the same host on different ports, and map <service>.rcos.io to them?

Yeah, Caddy is a reverse proxy like NGINX or similar. It just takes different ports and maps them to domains or paths.

I picked it because I quite like it. It's easy to configure, performant, and does automatic HTTPS out of the box.

> One important question: How soon can this be deployed? How many things have to be done? Do we need access to rcos.io, the right DigitalOcean, etc. before any of this can go up?

This can be deployed hopefully this week. The blockers are listed below, but generally speaking things can probably be figured out pretty quickly.

### Things we still need

- Namecheap login for DNS
- Billing setup for DO
- Access to the old DO droplet for #8
- Access to old RPI server for #8

### Things to figure out

- How is the server gonna be configured? What OS? How much CPU/RAM/disk?
- Related to above, are we going to use a managed or custom Postgres? Managed is more expensive but more robust.
- In general what is our infrastructure budget? Can we secure additional funding if needed?

> What if that doesn't happen by the start of the semester?

I don't know...
We should hopefully have a couple of extra weeks at the beginning of the semester as things get rolling, if we need it.

**Comment by Apexal** [comment]
An important use of the database/api will be setting up the Discord server channels for project pairing and then small groups. I'll have to make sure we have *some* database and server to store the info at that point.

**Comment by rushsteve1** [comment]
All else fails we can use a temporary server and migrate the DB later. Bit of a pain but doable if we have to.

**Review by Apexal — APPROVED** [review]

**Pull request merged**
